export const employeeList =[
    {
      id: 1,
      firstName: 'Manoj',
      lastName: 'Ramisetty',
      Phone:'1234561265',
      dateOfBirth:'12Jan1997',
      gender:'male',
      Email:'manoj@gmail.com',
      branch:'Madhapur',
      department:'ttd',
      role: 'Developer',
      reportingTo:'Prabhakar',
      amount:'500',
      skills: 'React',
      notes:'',
    },
    {
      id: 2,
      firstName: 'Sandeep',
      lastName: 'Pureti',
      Phone:'1234234535',
      dateOfBirth:'29May1997',
      gender:'male',
      Email:'sandeep@gmail.com',
      branch:'Madhapur',
      department:'ttd',
      role: 'Developer',
      reportingTo:'Prabhakar',
      // amount:'300',
      skills: 'React',
      notes:'',
    },
    {
      id: 3,
      firstName: 'Suma',
      lastName: 'Vegesna',
      Phone:'1239813535',
      dateOfBirth:'15April1997',
      gender:'female',
      Email:'suma@gmail.com',
      branch:'Madhapur',
      department:'ttd',
      role: 'Developer',
      reportingTo:'Prabhakar',
      amount:'300',
      skills: 'React',
      notes:'',
    },
    {
      id: 4,
      firstName: 'Jyothi',
      lastName: 'Tadala',
      Phone:'5487498535',
      dateOfBirth:'6Jan1997',
      gender:'female',
      Email:'jyothi@gmail.com',
      branch:'Madhapur',
      department:'ttd',
      role: 'Developer',
      reportingTo:'Vamsi',
      // amount:'300',
      skills: 'React',
      notes:'',
    },
    {
      id: 5,
      firstName: 'Rajeswari',
      lastName: 'Golla',
      Phone:'6305023535',
      dateOfBirth:'23July1997',
      gender:'female',
      Email:'rajeswari@gmail.com',
      branch:'Madhapur',
      department:'ttd',
      role: 'Developer',
      reportingTo:'Vamsi',
      // amount:'300',
      skills: 'React',
      notes:'To work in a challenging environment and to utilize my skills for the growth of myself and the organization.',
    },
    {
      id: 6,
      firstName: 'Sirish',
      lastName: 'Sunkara',
      Phone:'7891238535',
      dateOfBirth:'17Aug1997',
      gender:'male',
      Email:'sirish@gmail.com',
      branch:'Madhapur',
      department:'ttd',
      role: 'Developer',
      reportingTo:'Vamsi',
      // amount:'300',
      skills: 'React',
      notes:'',
    },
    {
      id: 7,
      firstName: 'Praveen',
      lastName: 'Patlolla',
      Phone:'2327498531',
      dateOfBirth:'13Jan1997',
      gender:'male',
      Email:'praveen@gmail.com',
      branch:'Madhapur',
      department:'ttd',
      role: 'Developer',
      reportingTo:'Vamsi',
      // amount:'300',
      skills: 'React',
      notes:'',
    },
    {
      id: 8,
      firstName: 'Krishna Teja',
      lastName: 'P',
      Phone:'4353449855',
      dateOfBirth:'2Nov1997',
      gender:'male',
      Email:'krishnateja@gmail.com',
      branch:'Madhapur',
      department:'ttd',
      role: 'Developer',
      reportingTo:'Prabhakar',
      // amount:'300',
      skills: 'React',
      notes:'',
    },
    {
      id: 9,
      firstName: 'Sai Teja',
      lastName: 'k',
      Phone:'7891398535',
      dateOfBirth:'15dec1997',
      gender:'male',
      Email:'saiteja@gmail.com',
      branch:'Madhapur',
      department:'ttd',
      role: 'Developer',
      reportingTo:'Prabhakar',
      // amount:'300',
      skills: 'React',
      notes:'',
    },
  ];
